version: "3.5"
services:
  gameplayweb:
    build: .
    labels:
      SERVICE_5000_NAME: QuizEngine
    networks:
      - quiz-engine-network
    ports:
      - "5000"
networks:
  quiz-engine-network:
    name: quizrt-network
    external: true