version: "3"
services:
  gameplaydb:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Your_password123
    image: microsoft/mssql-server-linux
    networks:
      - quiz-engine-network
    ports:
      - "1433"
  gameplayweb:
    build: .
    labels:
      SERVICE_5000_NAME: QuizEngine
    networks:
      - quiz-engine-network
    environment:
      SQLSERVER_HOST: Server=gameplaydb;Database=Quiztest3DBLinux;User=sa;Password=Your_password123
    depends_on:
      - gameplaydb
    ports:
      - "5000"
networks:
  quiz-engine-network:
    name: quizrt-network
    external: true