version: "3.5"
services:
  gameplayweb:
    build: .
    labels:
      SERVICE_5000_NAME: QuizEngine
    networks:
      - quiz-engine-network
    environment:
      SQLSERVER_HOST: Server=gameplaydb;Database=Quiztest3DBLinux;User=sa;Password=Your_password123
    ports:
      - "5000"
networks:
  quiz-engine-network:
    name: quizrt-network
    external: true